version: '3'
services:
  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=passwort
    volumes:
      - couchdbdata:/opt/couchdb/data

volumes:
  couchdbdata:
